/**
 * Standard error codes used across all API responses.
 * The `code` field in error envelopes always uses one of these values.
 */

export enum ErrorCode {
  // Generic
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  GONE = 'GONE',

  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
  EMAIL_TAKEN = 'EMAIL_TAKEN',
  TWO_FACTOR_REQUIRED = 'TWO_FACTOR_REQUIRED',

  // Restaurants
  RESTAURANT_NOT_FOUND = 'RESTAURANT_NOT_FOUND',
  RESTAURANT_SLUG_TAKEN = 'RESTAURANT_SLUG_TAKEN',
  RESTAURANT_NOT_APPROVED = 'RESTAURANT_NOT_APPROVED',
  RESTAURANT_ALREADY_CLAIMED = 'RESTAURANT_ALREADY_CLAIMED',
  NOT_RESTAURANT_MEMBER = 'NOT_RESTAURANT_MEMBER',

  // Menu
  MENU_ITEM_NOT_FOUND = 'MENU_ITEM_NOT_FOUND',
  MENU_SECTION_NOT_FOUND = 'MENU_SECTION_NOT_FOUND',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  TAG_NOT_FOUND = 'TAG_NOT_FOUND',

  // Templates / QR
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
  QR_CODE_NOT_FOUND = 'QR_CODE_NOT_FOUND',
  TEMPLATE_SANITIZATION_FAILED = 'TEMPLATE_SANITIZATION_FAILED',

  // Media
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  UPLOAD_FAILED = 'UPLOAD_FAILED',

  // Orders (Phase 2)
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_CANNOT_BE_CANCELLED = 'ORDER_CANNOT_BE_CANCELLED',
  INVALID_ORDER_TRANSITION = 'INVALID_ORDER_TRANSITION',
  CART_EMPTY = 'CART_EMPTY',
  ITEM_UNAVAILABLE = 'ITEM_UNAVAILABLE',

  // Payments (Phase 2)
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  INSUFFICIENT_CREDIT = 'INSUFFICIENT_CREDIT',
  PROMO_CODE_INVALID = 'PROMO_CODE_INVALID',
  PROMO_CODE_EXPIRED = 'PROMO_CODE_EXPIRED',
  PROMO_USAGE_LIMIT_REACHED = 'PROMO_USAGE_LIMIT_REACHED',

  // Feature flags
  FEATURE_DISABLED = 'FEATURE_DISABLED',

  // Billing
  PLAN_NOT_FOUND = 'PLAN_NOT_FOUND',
  PLAN_PRICE_NOT_FOUND = 'PLAN_PRICE_NOT_FOUND',
  SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND',
  SUBSCRIPTION_ALREADY_ACTIVE = 'SUBSCRIPTION_ALREADY_ACTIVE',
  SUBSCRIPTION_NOT_ACTIVE = 'SUBSCRIPTION_NOT_ACTIVE',
  SUBSCRIPTION_NOT_PAUSED = 'SUBSCRIPTION_NOT_PAUSED',
  INVOICE_NOT_FOUND = 'INVOICE_NOT_FOUND',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  COUPON_NOT_FOUND = 'COUPON_NOT_FOUND',
  COUPON_INVALID = 'COUPON_INVALID',
  COUPON_EXPIRED = 'COUPON_EXPIRED',
  COUPON_LIMIT_REACHED = 'COUPON_LIMIT_REACHED',
  COUPON_ALREADY_REDEEMED = 'COUPON_ALREADY_REDEEMED',
  REFUND_REQUEST_NOT_FOUND = 'REFUND_REQUEST_NOT_FOUND',
  REFUND_WINDOW_EXPIRED = 'REFUND_WINDOW_EXPIRED',
  REFUND_AMOUNT_EXCEEDED = 'REFUND_AMOUNT_EXCEEDED',
  REFUND_ALREADY_DECIDED = 'REFUND_ALREADY_DECIDED',
  FEATURE_LIMIT_REACHED = 'FEATURE_LIMIT_REACHED',
  CHAPA_ERROR = 'CHAPA_ERROR',
  WEBHOOK_INVALID_SIGNATURE = 'WEBHOOK_INVALID_SIGNATURE',
}
